### ISSUE TITLE
Namespace issue when using kemalyst-validators & kemalyst-model

### ISSUE THREAD

**Issue by andrewzah** [drujensen/kemalyst-validators#1]
Both have a variable `errors`. If you include `kemalyst-validators`,
```crystal
errors << validator[:message]
```
fails, because errors is defined as an `Array(String)?` in `kemalyst-model`.

**Comment by drujensen** [comment]
thanks for reporting this.  I am still working on the integration with kemalyst-model.

**Comment by drujensen** [comment]
This should now be fixed with the latest release v0.2.2 of kemalyst-model and kemalyst.
